version: '3.9'
services:
  django_db:
    container_name: django_db
    image: postgres:15.2-bullseye
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.db
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ipankratov" ]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/web/dist:ro
      - ./static:/usr/web/static:ro
      - ./media:/usr/web/media:ro
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      
  django:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: django
    command:
      sh ./dev.start.sh
    volumes:
      - ./web/backend:/usr/backend
      - ./dist:/usr/backend/dist
    env_file:
      - ./web/.env
    depends_on:
      - django_db
    tty: true
    expose:
      - "8000"
    links:
      - django_db:django_db
volumes:
  postgres_data:
